version: '3'

services:
  backend:
    restart: always
    build: ./backend
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # general settings
      SECRET_KEY: '(#w*9%!t+af^do-^k9&e%*m9l*_p-73!hqpzv0lsr)*(-8zj9a'
      DEBUG: 'True'
      ALLOWED_HOSTS: '*'
      # database
      DB_NAME: docker
      DB_USER: docker
      DB_PASSWORD: docker
      DB_HOST: 'db'
      DB_PORT: '5432'
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
