# Generated by Django 4.2.4 on 2023-08-29 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniblogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniblog',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miniblogs.miniblog'),
        ),
    ]
